### PR TITLE
add --experimental-fetch option

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by ljharb** [comment]
i'd really rather not; node using the name "fetch" when it can't possibly be compliant is an abomination.

**Comment by caub** [comment]
please let's do, anyway in the bot we would just play with it for testing the API and using data-urls, it's educational. I understand your complaints about it, but we have plenty controversial babel plugins loaded as well

**Comment by ljharb** [comment]
such as?

**Comment by caub** [comment]
@babel/plugin-proposal-partial-application
@babel/plugin-proposal-pipeline-operator

those 2

**Comment by ljharb** [comment]
Pipeline is stage 2, that’s not controversial; altho i agree we should disable PFA.

**Comment by caub** [comment]
it'll be enabled by default on node18 btw, so closing

**Comment by ljharb** [comment]
gross

**Pull request closed without merging**
